### ISSUE TITLE
FMT_SMF.1/WLAN bridging control & MDF

### ISSUE THREAD

**Issue by woodbe** [commoncriteria/wlanclient#10]
The management option of:

> disable wireless network bridging capability (for example, bridging a connection between the WLAN and cellular radios on a smartphone so it can function as a hotspot)

has a related MDF management option of:

> 41. enable/disable [selection: Hotspot functionality authenticated by [selection: pre-shared key, passcode, no authentication], <more here>]

In the past (as this requirement was in the EP), it wasn't clear that there needed to be a specific way to control the ability to set (or not set) a hotspot. Is the expectation at this point that it MUST be possible to disable the hotspot, and then leave the option of a hotspot configuration (if one can be specifically enabled) up to the MDF? It would seem more consistent to put all the hotspot configurations in one PP (which one is not obvious in either case to me).

**Comment by kgal** [comment]
I replaced the old management function with (essentially) the one that was in the MDF PP, as I believe all GPOSes can support this requirement.

**Comment by woodbe** [comment]
That works for me. Now we just need to make one for the BT Module and leave the USB one in the MDF.

**Comment by kgal** [comment]
I added an issue to the MDF about removing this bridging management function.
