### ISSUE TITLE
FMT_SMF.1/WLAN wireless frequency band

### ISSUE THREAD

**Issue by woodbe** [commoncriteria/wlanclient#11]
The management requirement:

> set wireless frequency band to [selection: 2.4 GHz, 5 GHz, 6 GHz]

implies that it is for the whole device, that the device can only be configured to work on a specific band regardless of the networks available. On Android devices this setting is not tied to the whole device but to a specific network configuration. So it is not possible to say the device can only work on the 5 GHz band, but it is possible to specify that a network must be available on the 5 GHz band to allow it to connect.

It would seem that this should be placed under the security policy for each configured network. Otherwise this would seem to need to be optional, and moved under the selection list below so the ability to select the option would only be available where applicable.

**Comment by lewyble** [comment]
Overall, yes the goal was to limit the frequency band(s) that the device could connect to. However, we may be able to achieve the same end goal by moving it under the specific network configuration (FMT_SMF function 1). Would it be possible to limit the networks that a device could connect to (FMT_SMF function 2) and then as part of the configured security policy (FMT_SMF function 1) limit the frequency in which the device could connect to each of those networks? So in essence it is configuring the device to be able to only connect to networks within a specific frequency band.

**Comment by woodbe** [comment]
Yes, that is along the lines of what I was thinking. If you limit the networks that can be used to only those specified by the admin, you could then restrict the frequencies used for any particular network (while still allowing you to tailor the frequency if needed for different networks).

So in short, setting item 4 as one of the bullets in item 1 would get to the same place, just in a different manner. 

This is likely a better way to handle it as if the device can set it globally it would still meet the requirement (of setting it for the individual connections) by them using the global setting, but the other way around (where it can only be set on an individual connection) doesn't seem to meet the intent for a global setting (it could be interpreted that way, but I think it is better to interpret a global setting as a default than it is to go the other way around).

**Comment by kgal** [comment]
I believe I made the change that you (Brian) suggested. 
https://commoncriteria.github.io/wlanclient/wlanclient-release-linkable.html#FMT_SMF.1.1/WLAN

**Comment by woodbe** [comment]
This looks good to me.
