### ISSUE TITLE
Privacy concerns with auditing

### ISSUE THREAD

**Issue by woodbe** [commoncriteria/wlanclient#12]
Several of the audit requirements specify that the SSID (or other identifier) of the endpoint be available in the logs. The concern (especially for mobile devices) is that this type of information can be used to potentially determine location data about a user. While this may not be a concern on a corporate-owned device, there are now many efforts ongoing related to BYOD or similar that may also be subject to CC evaluation (and hence these requirements), where-in the privacy of the user is a high concern.

The question then is whether there is a way that these messages can be recorded but with less detail such that it could be possible for the administrator to make determinations about the Wi-Fi network, but which would be more difficult for someone else. An example would be to show only the last several characters of the Wi-Fi MAC address, and maybe be paired with a certificate check message.

**Comment by macahill** [comment]
See **Additional Audit Record Contents, FTA_WSE_EXT.1** for update that was made to reflect this.

**Comment by woodbe** [comment]
I like that, but the way it is written, is it acceptable to provide the last 2 octets or is it 3 or more? I know that at Google, 2 octets has been the standard for this and want to be clear that 2 is (or isn't) acceptable.

**Comment by kgal** [comment]
It took me a more tries than I wanted, but I think the bullet is clearer now. Please review when you (@woodbe) get the chance.  

https://commoncriteria.github.io/wlanclient/wlanclient-release-linkable.html#period_164

**Comment by woodbe** [comment]
That is exactly the clarity I am looking for. Thanks
