### ISSUE TITLE
FCS_CKM.2/WLAN Cryptographic Key Distribution (GTK)

### ISSUE THREAD

**Issue by macahill** [commoncriteria/wlanclient#2]
**Comment**
With regards to cryptographic key distribution, IEEE 802.11-2016 is referenced, which has been superseded by IEEE 802.11-2020 

**Auditable Events**
Key management systems, to check all keys are compliant

**Comment by jfisherbah** [comment]
SME discussion determined auditable events not necessary.

To address feedback on the requirement, the following is proposed:

FCS_CKM.2/WLAN The TSF shall **decrypt Group Temporal Key** in accordance with a specified cryptographic key distribution method [_AES Key Wrap (as defined in RFC 3394) in an EAPOL-Key frame (as defined in IEEE 802.11-2020 for the packet format and timing considerations_] **and does not expose the cryptographic keys**.

**Comment by kgal** [comment]
The proposal was added. The requirement currently points to IEEE 802.11-2012 which appears to be the correct one (as the IEEE 802.11-2020 doesn't appear to define an EAPOL-Key frame).
