### ISSUE TITLE
FIA_PAE_EXT.1 Identification and Authentication (FIA)

### ISSUE THREAD

**Issue by macahill** [commoncriteria/wlanclient#3]
**Comment**
IEEE 802.1X-2020 is referenced, which has been superseded by IEEE 802.1X-2020

**Auditable Event(s)**
Failure to establish EAP-TLS session

**Comment by jfisherbah** [comment]
To address this, it is proposed to update the 802.1X-2020 reference in the FIA_PAE_EXT.1 app note to IEEE 802.1X-2020.

Note that no change to auditable events are proposed here because “Failure to establish an EAP-TLS session” is already covered under FCS_TLSC_EXT.1/WLAN.

**Comment by jfisherbah** [comment]
802.1X-2010 references changed to 802.1X-2020 throughout
