### ISSUE TITLE
FMT_SMF.1/WLAN Security Management

### ISSUE THREAD

**Issue by macahill** [commoncriteria/wlanclient#4]
**Comment**
Mandate "Disable wireless network bridging capability (for example, bridging a connection between the WLAN and cellular radios on a smartphone so it can function as a hotspot)".  
All other items remain selectable

**Comment by jfisherbah** [comment]
To address this, it is proposed to move the selection in question up to the mandatory bullets.

Additionally, the following separate feedback on FMT_SMF.1/WLAN was received: "Update FMT_SMF.1 to allow the management function of configuring the frequency band, including 6 GHz to support Wi-Fi 6E"

To address this second item, it is proposed to add the following to FMT_SMF.1/WLAN as a mandatory bullet (i.e. before the selection):

* set wireless frequency band to [**selection:** _2.4 GHz, 5 GHz, 6 GHz_].

**Comment by jfisherbah** [comment]
FMT_SMF.1/WLAN updated per feedback above
