### ISSUE TITLE
FTA_WSE_EXT.1 TOE Access

### ISSUE THREAD

**Issue by macahill** [commoncriteria/wlanclient#5]
**Auditable Event(s)**
Attempts to connect to unknown outside networks

**Comment by jfisherbah** [comment]
Per subsequent discussions this does not need to be added. FTA_WSE_EXT.1 already requires “all attempts to connect to access points” to be audited. The actual FTA_WSE_EXT.1 SFR says that the TSF can only connect to acceptable networks. Based on that, it’s reasonable to assume any mechanism that could be used to connect to an unknown outside network would be disabled or unavailable, and so there would never be such an event to get audited in the first place.

**Comment by jfisherbah** [comment]
closed per previous response
