### ISSUE TITLE
FTP_ITC.1/WLAN Trusted Path/Channels

### ISSUE THREAD

**Issue by macahill** [commoncriteria/wlanclient#6]
**Comment**
IEEE 802.11-2016 is referenced, which has been superseded by IEEE 802.11-2020

**Comment by jfisherbah** [comment]
Proposed update is to replace 802.11-2016 with 802.11-2020 in FTP_ITC.1.1/WLAN

**Comment by kgal** [comment]
Currently, there are no references to 802.11-2016 in the document.
