### ISSUE TITLE
Management table structure change

### ISSUE THREAD

**Issue by woodbe** [commoncriteria/wlanclient#9]
The FMT_SMF.1/WLAN requirement is largely still a list with a note at the bottom about how the list relates to the tables in the various base-PP documents. The method used in the [Bluetooth PP](https://commoncriteria.github.io/pp/bluetooth/bluetooth-release.html#fmt) where it is laid out explicitly as a table that matches up with the MDF or OS PPs would be much preferred.

The BT tables label the individual requirements with a BT-xx, and these should have something like WL-xx to match up.

Putting these into a table would make it more consistent with the existing PPs.

**Comment by kgal** [comment]
This should be fixed:
https://commoncriteria.github.io/wlanclient/wlanclient-release.html#man_fmt
Please check it out when you get the chance.

**Comment by woodbe** [comment]
So the BT (and MDF) have 3 additional columns (User Only, Admin, Admin Only). In BT these are all optional, so is the expectation here that similarly these would all be optional?

This update with the numbering looks good, I just want to be clear on whether there are any specific mandatory checks that would be used for these other columns. For example I could see WLAN-2 being mandatory as an admin-only option (that the admin must be able to force that restriction). If everything is optional, maybe just a note to that effect so it is clear (without having to make the table).

**Comment by kgal** [comment]
I added an Admin and User column. 

https://commoncriteria.github.io/wlanclient/wlanclient-release.html#man_fmt

**Comment by woodbe** [comment]
That looks good. thank you
